config/routes.rb
Rails.application.routes.draw do
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 root "tests#index"
 devise_for :users
  resources :users, only:[:show]
  resources :tests 
  resources :comments, only:[:index, :create]
  
 
 end
 

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
has_one_attached :image
belongs_to :user
has_many :favorites, dependent: :destroy

with_options presence: true do
    validates :title
    validates :body
    validates :image
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :tests, dependent: :destroy
         has_many :favorites, dependent: :destroy
         
          def already_favorited?(test)
           self.favorites.exists?(test_id: test.id)
          end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @comment = Comment.new
  end
    
    def create
    Comment.create(comment_params)
    @comments = Comment.all
    end
  
  private
  def comment_params
  params.require(:comment).permit(:title, :body)
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_test, only: [:show, :edit, :update]
  
  def index
    @tests = Test.all.order(created_at: :desc).page(params[:page]).per(6)
  end
  
  def show
     
  end

  def new
  @test = Test.new
  end

  def create
    @test = Test.new(test_params)
    @test.user_id = current_user.id
     if @test.save
      redirect_to root_path(@test)
    else
      render :new
     end
  end
  
  def edit
  
  end
  
  def update
  if @test.update(test_params)
    redirect_to root_path(@test), notice: '更新できました'
  else
    render :edit,　alert: '更新できませんでした'
  end
  end
  
  def destroy
    test = Test.find(params[:id])
    test.destroy 
    redirect_to root_path, notice: '削除できました'
  end 

  private
  def find_test
    @test = Test.find(params[:id])
  end
  
  def test_params
     params.require(:test).permit(:title, :body, :image)
  end  

  def update_params
     params.require(:test).permit(:title, :body, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
<div class="card">
    <div class="card-body">
      <p class="card-text">NICKNAME: 　<%= comment.title %>様</p>
      <span class="card-text"><small>ご意見・ご感想<%= simple_format comment.body %></small>
    </span>
  </div>
<% end %>

app/views/comments/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.comments').html("<%= escape_javascript(render 'comments', comments: @comments) %>")

app/views/comments/index.html.erb
<!-- Button trigger modal -->
<div class="container mt-5">
  <div class="row">
    <div class="col-3">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
       ご感想・ご意見はこちらからお願いいたします
      </button>
      <p class="onegai">※万が一不適切なコメントがございましたら私の方で削除いたします。ご了解のほどお願いいたします。</p>
      </div>
      <div class="col-9 comments">
      <%= render 'comments', comments: @comments %>
      </div>
    </div>
 </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">暖かいコメントお願いします</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for @comment, remote: true do |f| %>
      <div class="modal-body">
          <div class="form-group">
            <%= f.label :title, "NICKNAME" %>
            <%= f.text_field :title,class:"form-control"%>
          </div>
          <div class="form-group">
            <%= f.label :body, "ご意見・ご感想" %>
            <%= f.text_area :body,class:"form-control"%>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= f.submit "投稿する",class:"btn btn-primary" %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test2</title>
    <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <script data-ad-client="ca-pub-1677896541685029" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    </head>
  <body>
   <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">最強の係長のホームページにようこそ</a>
         <div class="hamburger-menu">
          <input type="checkbox" id="menu-btn-check">
          <label for="menu-btn-check" class="menu-btn"><span></span></label>
          <div class="menu-content">
         ◉　MENU　◉
         <ul>
           <li>
         <%= link_to "最強の係長のプロフィール", user_path(:id)%>
           </li>
           <li>
         <%= link_to "ご感想・ご意見はこちらから", comments_path%>    
           </li>
          </ul>
        </div>
        </div>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
   <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<div class="container">
  <h1 class="txt-center">最強の係長のプロフィール</h1>
   <div class="pro_img">
   <%= image_tag'mac.jpg', size: '250x250' %>
   <%= image_tag'yome.jpeg', size: '250x250' %>
   <%= image_tag'shiro.jpg', size: '250x250' %>
   </div>
   <h2 class="txt-sub">プロフィール</h2>
<ul>
  <li>年齢：５１歳</li>
  <li>住まい：千葉県</li>
  <li>家族：嫁さんとワンコ１匹</li>
  <li>性格：これと決めたらやり切る！</li>
  <li>趣味：プログラミング</li>
  <li>目標：定年後家族で日本一周旅行！</li>
</ul>
＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
　　　　　　　  <h2 class="title">生い立ち</h2> 

<ul>
  <li>18歳 高校卒業後</li>
  <p>調理師の専門学校に通うが夏休みに遊び呆けてしまって、夏休み後退学する</p>
  <P>その後バイト先のファミリーレストランで朝の6時から夜の11時まで働き詰める</P>
  <li>20歳　お金を手にして調子こく</li>
  <p>1年で120万円を貯めることができ、運転免許取得と70万円の中古を購入！</p>
  <p>車を買ったことを3ヶ月間、両親にも伝えておらず、その後ほぼ両親から放置される</p>
  <li>22歳　某輸入車メーカーに就職</li>
  <p>自動車会社にに入社した理由: 中古車販売店で勤めていた友人のところに遊びに行ったところ</p>
  <p>自動車を査定している友達の姿がカッコ良かったから。　ただそれだけです</p>
  <li>30歳で店長に昇格</li>
  <P>ミレニアム時期に入っており、不景気な最中の店長昇格のため、世間の厳しい風当たりに合う</P>
  <p>あの時期に戻りたくはないが、今となってはあの経験があったからこそ強いメンタルも養われたのだと思う</p>
  <li>37歳で退職</li>
  <P>いよいよ日本における輸入車自動車会社の限界を知り、退職を決断！ かなり悩みました</P>
  <li>退職から無職の生活を3ヶ月味わう</li>
  <p>人生初めて長期連休というのを味わう！　当時ハマっていたゴルフにうつつを抜かしてしまう</p>
  <P>退職金と失業保険を頼りに遊びほうける</P>
  <li>38歳いよいよ再就職!!</li>
  <P>以前より興味があった通信会社に就職。東京の赤坂見附まで電車通勤するが</P>
  <p>満員電車になれず挫折！　やはり自動車業界に復帰をしたい欲が出てしまい</p>
  <p>半年で退職をする。</p>
  <li>40歳手前で再々就職活動！</li>
  <p>もう転職をするのはタイムリミットの39歳！　自動車ディーラーに再就職を希望していたので</p>
  <p>毎日、職業安定所に通い、パソコンと睨めっこする日々を暮らす。</p>
  <P>そんなこんなで職安に通い詰めて約２ヶ月目で今の会社に就職することができる　良かった！！</P>
  <li>44際で初婚！</li>　
  <p>なんと19歳の離れた年の差婚を果たす！　その後35年ローンで一軒家を購入！</p>
  <p>長生きをしないといけないという責任感が今以上に湧いてきた！　新婚旅行は沖縄！　楽しかった！</p>
  <li>48歳で係長に昇格</li>
  <p>この歳になると会社からの要求は高い！　現場で営業として自動車を販売しつつ</p>
  <p>営業兼教育係長として、いかんなく今までの経験と知識を後輩に伝える役割を担う</p>
  <li>50歳プログラミングに出会う</li>
  <P>2020年コロナの影響で休日は読書に没頭。そんな中プログラミングに出会う</P>
  <p>8月にテックキャンプ入所　今に至る</p>
  
</ul>

</div>
 